## 3 week Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수**: 1차원 벡터 (`np.array`)
- **반환값**: 인자로 주어진 벡터의 L2 Norm값 (`number`)

**L2 norm** = $\sqrt{\sum_{i=1}^{n} x_{i}^{2}}$ 

In [32]:
import numpy as np

def get_L2_norm_np(vec):  
    return np.linalg.norm(vec)


def get_L2_norm(vec):
    return np.sqrt(np.sum(vec**2))


arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("행렬 arr:")
print(arr, '\n')
print("np를 사용한 L2 norm: {}".format(get_L2_norm_np(arr)))
print("np를 사용하지 않은 L2 norm: {}".format(get_L2_norm(arr)))

행렬 arr:
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

np를 사용한 L2 norm: 16.881943016134134
np를 사용하지 않은 L2 norm: 16.881943016134134


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()`를 작성하세요

- **매개변수**: 2차원 벡터(`np.array`)
- 반환값: 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환

**행렬 A의 역인 $A^{-1}$이 존재하지 않을 때,  
즉, 역행렬이 존재하지 않을 때 행렬 A를 singular matrix라고 한다.**

**역행렬이 존재하지 않을 조건은 행렬식 == 0이다.  
즉, det(A) == 0이면 행렬 A의 역행렬은 존재하지 않는다.**

In [41]:
def is_singular(mat):
    if np.linalg.det(mat) == 0:
        return True
    else:
        return False


arr = np.array([[1,2],[3,4]])
arr2 = np.array([[-2,-1],[2,1]])

print(np.linalg.det(arr))    # 행렬 arr의 행렬식 det(arr)
print(is_singular(arr))      # 행렬식이 0이 아니므로 역행렬이 존재하는 matrix이다.
                             # 따라서 False를 반환
print("\n")
print(np.linalg.det(arr2))   # 행렬 arr2의 행렬식 det(arr2)
print(is_singular(arr2))     # 행력식이 0이므로 역행렬이 존재하지 않는 singular matrix이다.
                             # 따라서 True를 반환

-2.0000000000000004
False


0.0
True
