In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])

arr

array([1, 2, 3])

In [11]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr.shape

(3,)

In [12]:
arr_2d.shape

(3, 3)

### vector와 Scalar 사이의 연산 ###
벡터의 각 원소에 대해서 연산을 진행

In [15]:
x = np.array([1,2,3])
c = 5

print("더하기: {}".format(x + c))
print("빼기 : {}".format(x - c))
print("곱하기: {}".format(x * c))
print("나누기: {}".format(x / c))

더하기: [6 7 8]
빼기 : [-4 -3 -2]
곱하기: [ 5 10 15]
나누기: [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산 ###
벡터의 같은 인덱스끼리 연산이 진행!!

In [18]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print("더하기: {}".format(y + z))
print("빼기 : {}".format(y - z))
print("곱하기: {}".format(y * z))
print("나누기: {}".format(y / z))

더하기: [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기: [  2  27 100]
나누기: [0.5        0.33333333 0.25      ]


### Array의 Indexing ###
Array에서 특정 위치의 원하는 원소를 가지고 오고 싶다면

In [20]:
w = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(w)
print(w[0,0])
print(w[2,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
12


### Array Slicing ###

In [21]:
w = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 배열에서 2,3,6,7을 가져오려고 할 때

w[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [22]:
w[0:2, 0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
w[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
w[0:3, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [25]:
w[:, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

### Array의 Broadcasting ###
numpy의 연산

기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능  
하지만 만약 피연산자가 연산이 가능하도록 변환이 가능하다면 연산이 가능.  
이를 **Broadcasting** 이라고 한다.

1. M $\times$ N, M $\times$ 1
2.
3. M $\times$ 1, 1 $\times$ N

### 1. M $\times$ N, M $\times$ 1 ###

In [27]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,1,0])

print(a + x)

[[1 3 3]
 [4 6 6]
 [7 9 9]]


위의 예제에서 np.array()는 기본적으로 행벡터이기 때문에 x는 열벡터가 아닌 행벡터로 선언되었다.  
따라서 M $\times$ 1 이 아닌 1 $\times$ M이 되었다.  
행벡터를 열벡터로 바꿔주기 위해서는 전치를 시켜줘야 한다.

In [28]:
x = x[:, None]    # x를 전치

print(a + x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


### 2. M $\times$ N, 1 $\times$ N ###

In [29]:
y = np.array([0, 1, -1])

print([a * y])

[array([[ 0,  2, -3],
       [ 0,  5, -6],
       [ 0,  8, -9]])]


### M $\times$ 1, 1 $\times$ N ###

In [30]:
t = np.array([1, 2, 3])    # 열벡터로 바꿔줘야 함!
t = t[:, None]    # Transpose

u = np.array([2, 0, -2])

print(t + u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## Numpy와 선형대수

### 1. basics ###

### 영벡터(행렬) ###

- 원소가 모두 0인 벡터(행렬)
- `np.zeros(dim)`을 통해 생성, dim은 값, 혹은 튜플 (,)

In [33]:
np.zeros(1)

array([0.])

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### 일벡터 (일행렬)
- 원소가 모두 1인 벡터(행렬)
- `np.ones(dim)`을 통해 생성

In [35]:
np.ones(2)

array([1., 1.])

In [37]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬(diagonal matrix)

- Main diagonal을 제외한 성분이 0인 행렬
- `np.diag(main_diagonal)`을 통해 생성

In [38]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [39]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등행렬 

- Main diagonal이 1인 대각행렬
- `np.eye(n, [dtype=int, uint, float, complex, ...])`를 사용

In [40]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [41]:
np.eye(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 행렬곱 (dot product)

- 행렬간의 곱연산
- `np.dot()` 또는 `@` 사용

In [44]:
mat_1 = np.array([[2,4],[2,3]])
mat_2 = np.array([[7,9],[0 ,6]])

mat_1.dot(mat_2)

array([[14, 42],
       [14, 36]])

In [45]:
mat_1 @ mat_2

array([[14, 42],
       [14, 36]])

### 트레이스(trace)

- Main diagonal의 합
- `np.trace()`를 사용

In [46]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr.trace()

15

In [48]:
np.eye(2, dtype=int).trace()

2

### 행렬식 (determinant)

- 행렬을 대표하는 값들 중 하나 (선형변환)
- 선형변환 과정에서 Vector의 Scaling 척도
- `np.linalg.det()`으로 계산

In [49]:
arr_2 = np.array([[2, 3],[1, 6]])

arr_2

array([[2, 3],
       [1, 6]])

In [50]:
np.linalg.det(arr_2)

9.000000000000002

In [53]:
arr_3 = np.array([[1, 4, 7],[2, 5, 8],[3, 6, 9]])

arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [54]:
np.linalg.det(arr_3)

0.0

### 역행렬

- 행렬 A에 대해 AB = BA = I를 만족하는 행렬 B $(B = A^{-1})$
- `np.linalg.inv()`으로 계산

In [55]:
mat = np.array([[1,4],[2,3]])

mat

array([[1, 4],
       [2, 3]])

In [56]:
mat_inv = np.linalg.inv(mat)

mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [57]:
mat @ mat_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

### 고유값과 고유벡터 (eigenvalue and eigenvector)

- 정방행렬 A에 대해 Ax = $\lambda$x를 만족하는 상수 $\lambda$와 이에 대응하는 벡터
- `np.linalg.eig()`으로 계산

In [58]:
mat = np.array([[2, 0, -2],[1, 1, -2], [0, 0, 1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [59]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

**Validation**

In [60]:
eig_val, eig_vec = np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [61]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [62]:
mat @ eig_vec[:, 0]   # Ax

array([0., 1., 0.])

In [63]:
eig_val[0] * eig_vec[:, 0] # (lambda)x

array([0., 1., 0.])